CapaPresentacionAdmin/Controllers/MantenimientoController.cs
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]

    public class MantenimientoController : Controller
    {
        public ActionResult Categorias()
        {
            return View();
        }

        public ActionResult Productos()
        {
            return View();
        }

        public ActionResult Marcas()
        {
            return View();
        }

        //---------*-*-*-*-Categorias-*-*-*-*-*-*---------\\
        #region Categorias

        [HttpGet]
        public JsonResult ListarCategorias()
        {
            List<Categoria> olista = new List<Categoria>();
            olista = new CNCategorias().Listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategorias(Categoria obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.IdCategoria == 0)
            {
                resultado = new CNCategorias().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CNCategorias().Editar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool resultado = false;
            string mensaje = string.Empty;

            resultado = new CNCategorias().Eliminar(id, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion
        //---------*-*-*-*-Marca-*-*-*-*-*-*---------\\
        #region Marca

        [HttpGet]
        public JsonResult ListarMarcas()
        {
            List<Marca> olista = new List<Marca>();
            olista = new CNMarca().Listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarcas(Marca obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.IdMarca == 0)
            {
                resultado = new CNMarca().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CNMarca().Editar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarcas(int id)
        {
            bool resultado = false;
            string mensaje = string.Empty;

            resultado = new CNMarca().Eliminar(id, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion
        //---------*-*-*-*-Producto-*-*-*-*-*-*---------\\
        #region Producto
        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> olista = new List<Producto>();
            olista = new CNProducto().Listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProducto(string obj, HttpPostedFileBase img)
        {
            string mensaje = string.Empty;
            bool exito = true;
            bool exitoImg = true;

            Producto productoss = new Producto();
            productoss = JsonConvert.DeserializeObject<Producto>(obj);

            decimal precio;
            if (decimal.TryParse(productoss.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-DO"), out precio))
            {
                productoss.Precio = precio;
            }
            else
            {
                return Json(new { exito = false, mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }

            if (productoss.IdProducto == 0)
            {
                int idProductoGen = new CNProducto().Registrar(productoss, out mensaje);
                if(idProductoGen != 0)
                {
                    productoss.IdProducto = idProductoGen;
                }else
                {
                    exito = false;
                }
            }
            else
            {
                exito = new CNProducto().Editar(productoss, out mensaje);
            }

            if (exito)
            {
                if(img != null)
                {
                    string rutaGuarda = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(img.FileName);
                    string nombreIMG = string.Concat(productoss.IdProducto.ToString(), extension);

                    try
                    {
                        img.SaveAs(Path.Combine(rutaGuarda, nombreIMG));
                    }
                    catch (Exception ex)
                    {
                        string msg = ex.Message;
                        exitoImg = false;
                    }

                    if (exitoImg)
                    {
                        productoss.RutaImagen = rutaGuarda;
                        productoss.NombreImagen = nombreIMG;
                        bool respuesta = new CNProducto().GuardarInfoImg(productoss, out mensaje);
                    }
                    else
                    {
                        mensaje = "Se guardo el producto, pero la imagen no se pudo guardar";
                    }
                }
            }

            return Json(new { exitos = exito, idGen = productoss.IdProducto, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult imgProducto(int id)
        {
            bool conversion;
            Producto producto = new CNProducto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();

            string textBase64 = CNRecursos.ConversionBase64(Path.Combine(producto.RutaImagen, producto.NombreImagen), out conversion);

            return Json(new
            {
                conversion = conversion,
                textBase64 = textBase64,
                extension = Path.GetExtension(producto.NombreImagen)
            },  
             JsonRequestBehavior.AllowGet
            );
        }

        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool resultado = false;
            string mensaje = string.Empty;

            // para obtener la img del producto cuando se borra borrar tambien la imagen
            Producto producto = new CNProducto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();
            string rutaImagen = Path.Combine(producto.RutaImagen, producto.NombreImagen);
            if (System.IO.File.Exists(rutaImagen))
            {
                try
                {
                    System.IO.File.Delete(rutaImagen);
                }
                catch (Exception ex)
                {
                    mensaje = $"Error al borrar imagen: {ex.Message}";
                    return Json(new { resultado = false, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
                }
            }

            resultado = new CNProducto().Eliminar(id, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

CapaPresentacionAdmin/Views/Mantenimiento/Categorias.cshtml
@{
    ViewBag.Title = "Categorias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Matenimiento</a></li>
    <li class="breadcrumb-item active">Categorias</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fas fa-list me-1"></i> Lista de Categorias
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button class="btn btn-outline-dark" onclick="abrirModal(null)">
                    Crear nueva categoria
                </button>
            </div>
        </div>
        <hr />

        <table id="tabla" class="display cell-border" style="width:100%;">
            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-light">
                <h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input id="txtId" type="hidden" value="0" />

                <div class="row g-1">
                    <div class="col-sm-6">
                        <label for="txtDescri" class="form-label">Descripción</label>
                        <input type="text" autocomplete="off" class="form-control" id="txtDescri">
                    </div>
                    <div class="col-sm-6">
                        <label for="selectActivo" class="form-label">Activo</label>
                        <select class="form-select" id="selectActivo">
                            <option value="1" selected>Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                </div>
            </div>
            <!--Alert-->
            <div class="row m-2">
                <div class="col-12">

                    <div id="mensajeError" class="alert alert-danger" role="alert">
                        A simple danger alert—check it out!
                    </div>

                </div>
            </div>

            <div class="modal-footer bg-dark text-light">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-outline-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts
    {
    <script>

        var tabladata;
        var filaselect;

            tabladata = $("#tabla").DataTable({
                responsive: true,
                ordering: false,
                "ajax": {
                    url: '@Url.Action("ListarCategorias", "Mantenimiento")',
                    type: "GET",
                    dataType: "json"
                },
                "columns": [
                    { "data": "Descripcion" },
                    {
                        "data": "Activo", "render": function (valor) {
                            if (valor) {
                                return '<span class="badge bg-success text-light">Si</span>'
                            } else {
                                return '<span class="badge bg-danger text-light">No</span>'
                            }
                        }
                    },
                    {
                        "defaultContent": '<button type="button" class="btn btn-info btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                            '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                        "orderable": false,
                        "searchable": false,
                        "width":"80px"
                    }
                ],
                language: {
                    url: "https://cdn.datatables.net/plug-ins/2.1.0/i18n/es-ES.json",
                }
            });

        function abrirModal(json) {

            $("#txtId").val(0);
            $("#txtDescri").val("");
            $("#selectActivo").val(1);

            $("#mensajeError").hide();

            if (json != null) {
                $("#txtId").val(json.IdCategoria);
                $("#txtDescri").val(json.Descripcion);
                $("#selectActivo").val(json.Activo == true ? 1 : 0 );
            }

            $("#formModal").modal("show");
        }
        //configuracion del boton editar
        $("#tabla tbody").on("click", '.btn-editar', function () {
            filaselect = $(this).closest("tr");

            var datos = tabladata.row(filaselect).data();

            abrirModal(datos);

        })
        //configuracion del boton eliminar
        $("#tabla tbody").on("click", '.btn-eliminar', function () {
            filaselect = $(this).closest("tr");

            var datos = tabladata.row(filaselect).data();
            nombre = datos.Descripcion;

            swal({
                title: "¿Estas seguro?" ,
                text: "No podras deshacer los cambios despues de haber eliminado a la Categoria: \"" + nombre + "\"",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Confimar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                closeOnCancel: false
            },
                function (isConfirm) {
                    setTimeout(function () {
                        if (isConfirm) {
                            swal("Eliminado", "La categoria " + nombre + " ha sido eliminado correctamente", "success");
                            jQuery.ajax({
                                url: '@Url.Action("EliminarCategoria", "Mantenimiento")',
                                type: "POST",
                                data: JSON.stringify({ id: datos.IdCategoria }),
                                dataType: "json",
                                contentType: "application/json; charset=utf-8",
                                success: function (data) {
                                    if (data.resultado) {
                                        tabladata.row(filaselect).remove().draw();
                                    } else {
                                        swal("No se pudo eliminar", "Error: " + data.mensaje, "error");
                                    }
                                },
                                error: function (error) {
                                    console.log(error)
                                }
                            })
                        }
                    }, 1500)
                    if (!isConfirm) {
                        swal("Cancelada", "La operacion ha sido cancelada", "error");
                    }
                });
        })

        function Guardar() {
            var categoria = {
                IdCategoria: $("#txtId").val(),
                Descripcion: $("#txtDescri").val(),
                Activo: $("#selectActivo").val() == 1 ? true: false
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarCategorias", "Mantenimiento")',
                type: "POST",
                data: JSON.stringify({ obj : categoria }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-dialog").LoadingOverlay("hide", true);

                    //nuevas categorias
                    if (categoria.IdCategoria == 0) {
                        //para guardar
                        if (data.resultado != 0) {
                            categoria.IdCategoria = data.resultado;
                            tabladata.row.add(categoria).draw(false);

                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    } else //edicion de categorias existentes
                    {

                        if (data.resultado) {
                            tabladata.row(filaselect).data(categoria).draw(false);
                            filaselect = null;

                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }

                },
                error: function (error) {
                    $(".modal-dialog").LoadingOverlay("hide", true);
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    //operaciones antes de terminar el envio del formulario
                    //pantalla de carga con loadingoverlay
                    $(".modal-dialog").LoadingOverlay("show", {
                        imageResizeFactor: 4,
                        text: "Cargando... Espere un momento por favor...",
                        size: 14
                    });
                }
            });
        }

    </script>
}

CapaPresentacionAdmin/Views/Mantenimiento/Marcas.cshtml
@{
    ViewBag.Title = "Marcas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Matenimiento</a></li>
    <li class="breadcrumb-item active">Marcas</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fas fa-tags me-1"></i> Lista de Marcas
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button class="btn btn-outline-dark" onclick="abrirModal(null)">
                    Agregar nueva marcas
                </button>
            </div>
        </div>
        <hr />

        <table id="tabla" class="display cell-border" style="width:100%;">
            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-light">
                <h5 class="modal-title" id="exampleModalLabel">Marca</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input id="txtId" type="hidden" value="0" />

                <div class="row g-1">
                    <div class="col-sm-6">
                        <label for="txtDescri" class="form-label">Descripción</label>
                        <input type="text" autocomplete="off" class="form-control" id="txtDescri">
                    </div>
                    <div class="col-sm-6">
                        <label for="selectActivo" class="form-label">Activo</label>
                        <select class="form-select" id="selectActivo">
                            <option value="1" selected>Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                </div>
            </div>
            <!--Alert-->
            <div class="row m-2">
                <div class="col-12">

                    <div id="mensajeError" class="alert alert-danger" role="alert">
                        A simple danger alert—check it out!
                    </div>

                </div>
            </div>

            <div class="modal-footer bg-dark text-light">
                <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-outline-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts
    {
    <script>

        var tabladata;
        var filaselect;

            tabladata = $("#tabla").DataTable({
                responsive: true,
                ordering: false,
                "ajax": {
                    url: '@Url.Action("ListarMarcas", "Mantenimiento")',
                    type: "GET",
                    dataType: "json"
                },
                "columns": [
                    { "data": "Descripcion" },
                    {
                        "data": "Activo", "render": function (valor) {
                            if (valor) {
                                return '<span class="badge bg-success text-light">Si</span>'
                            } else {
                                return '<span class="badge bg-danger text-light">No</span>'
                            }
                        }
                    },
                    {
                        "defaultContent": '<button type="button" class="btn btn-info btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                            '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                        "orderable": false,
                        "searchable": false,
                        "width":"80px"
                    }
                ],
                language: {
                    url: "https://cdn.datatables.net/plug-ins/2.1.0/i18n/es-ES.json",
                }
            });

        function abrirModal(json) {

            $("#txtId").val(0);
            $("#txtDescri").val("");
            $("#selectActivo").val(1);

            $("#mensajeError").hide();

            if (json != null) {
                $("#txtId").val(json.IdMarca);
                $("#txtDescri").val(json.Descripcion);
                $("#selectActivo").val(json.Activo == true ? 1 : 0 );
            }

            $("#formModal").modal("show");
        }
        //configuracion del boton editar
        $("#tabla tbody").on("click", '.btn-editar', function () {
            filaselect = $(this).closest("tr");

            var datos = tabladata.row(filaselect).data();

            abrirModal(datos);

        })
        //configuracion del boton eliminar
        $("#tabla tbody").on("click", '.btn-eliminar', function () {
            filaselect = $(this).closest("tr");

            var datos = tabladata.row(filaselect).data();
            nombre = datos.Descripcion;

            swal({
                title: "¿Estas seguro?" ,
                text: "No podras deshacer los cambios despues de haber eliminado a la Marca: \"" + nombre + "\"",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Confimar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                closeOnCancel: false
            },
                function (isConfirm) {
                    setTimeout(function () {
                        if (isConfirm) {
                            swal("Eliminado", "La marca " + nombre + " ha sido eliminado correctamente", "success");
                            jQuery.ajax({
                                url: '@Url.Action("EliminarMarcas", "Mantenimiento")',
                                type: "POST",
                                data: JSON.stringify({ id: datos.IdMarca }),
                                dataType: "json",
                                contentType: "application/json; charset=utf-8",
                                success: function (data) {
                                    if (data.resultado) {
                                        tabladata.row(filaselect).remove().draw();
                                    } else {
                                        swal("No se pudo eliminar", "Error: " + data.mensaje, "error");
                                    }
                                },
                                error: function (error) {
                                    console.log(error)
                                }
                            })
                        }
                    }, 1500)
                    if (!isConfirm) {
                        swal("Cancelada", "La operacion ha sido cancelada", "error");
                    }
                });
        })

        function Guardar() {
            var marca = {
                IdMarca: $("#txtId").val(),
                Descripcion: $("#txtDescri").val(),
                Activo: $("#selectActivo").val() == 1 ? true: false
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarMarcas", "Mantenimiento")',
                type: "POST",
                data: JSON.stringify({ obj : marca }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-dialog").LoadingOverlay("hide", true);

                    //nuevas marcas
                    if (marca.IdMarca == 0) {
                        //para guardar
                        if (data.resultado != 0) {
                            marca.IdMarca = data.resultado;
                            tabladata.row.add(marca).draw(false);

                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    } else //edicion de marca existentes
                    {

                        if (data.resultado) {
                            tabladata.row(filaselect).data(marca).draw(false);
                            filaselect = null;

                            $("#formModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }

                },
                error: function (error) {
                    $(".modal-dialog").LoadingOverlay("hide", true);
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    //operaciones antes de terminar el envio del formulario
                    //pantalla de carga con loadingoverlay
                    $(".modal-dialog").LoadingOverlay("show", {
                        imageResizeFactor: 4,
                        text: "Cargando... Espere un momento por favor...",
                        size: 14
                    });
                }
            });
        }

    </script>
}